# Generated by Django 3.2.8 on 2022-02-28 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='parking',
            name='password',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
