# Generated by Django 3.2.8 on 2022-02-28 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0002_parking_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parking',
            name='is_avaliable',
        ),
        migrations.AddField(
            model_name='parking',
            name='is_available',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='parking',
            name='email',
            field=models.EmailField(max_length=254, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='parking',
            name='password',
            field=models.CharField(blank=True, default=False, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='parking',
            name='username',
            field=models.CharField(max_length=10, null=True, unique=True),
        ),
    ]
