# Generated by Django 3.2.8 on 2022-02-28 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0003_auto_20220228_2311'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parking',
            name='password',
            field=models.CharField(blank=True, max_length=75, null=True),
        ),
    ]
