# Generated by Django 3.2.8 on 2022-02-28 21:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0004_alter_parking_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parking',
            name='password',
        ),
    ]
