# Generated by Django 3.2.8 on 2022-03-12 17:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('alien', '0014_auto_20220226_2135'),
        ('parking', '0005_remove_parking_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='parking',
            name='alien',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='alien_parking', to='alien.alien'),
        ),
        migrations.AddField(
            model_name='parking',
            name='name',
            field=models.CharField(blank=True, max_length=150, null=True, unique=True),
        ),
    ]
