# Generated by Django 3.2.8 on 2022-03-12 17:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('alien', '0014_auto_20220226_2135'),
        ('parking', '0006_auto_20220312_1920'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParkingProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified_at', models.DateTimeField(auto_now=True, null=True)),
                ('hidden', models.BooleanField(blank=True, default=False, null=True)),
                ('name', models.CharField(blank=True, max_length=150, null=True, unique=True)),
                ('username', models.CharField(max_length=10, null=True, unique=True)),
                ('email', models.EmailField(max_length=254, null=True, unique=True)),
                ('first_name', models.CharField(blank=True, max_length=255, null=True)),
                ('last_name', models.CharField(blank=True, max_length=255, null=True)),
                ('country', models.CharField(blank=True, choices=[('FRA', 'French'), ('SWZ', 'Switzerland'), ('BLG', 'Belgium')], max_length=75, null=True)),
                ('city', models.CharField(blank=True, max_length=75, null=True)),
                ('region_name', models.CharField(blank=True, max_length=20, null=True)),
                ('longitude', models.CharField(blank=True, max_length=20, null=True)),
                ('latitude', models.CharField(blank=True, max_length=20, null=True)),
                ('parking_number', models.IntegerField(blank=True, null=True)),
                ('is_available', models.BooleanField(default=True)),
                ('status', models.IntegerField(choices=[(200, 'New'), (201, 'Approved'), (400, 'Rejected')], default=200)),
                ('alien', models.OneToOneField(default=0, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='alien_parking', to='alien.alien')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.DeleteModel(
            name='Parking',
        ),
    ]
