# Generated by Django 3.2.8 on 2022-03-12 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0007_auto_20220312_1943'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parkingprofile',
            name='is_available',
            field=models.BooleanField(default=False),
        ),
    ]
