# Generated by Django 3.2.8 on 2022-03-12 18:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('alien', '0014_auto_20220226_2135'),
        ('parking', '0008_alter_parkingprofile_is_available'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parkingprofile',
            name='alien',
        ),
        migrations.CreateModel(
            name='ParkingBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified_at', models.DateTimeField(auto_now=True, null=True)),
                ('hidden', models.BooleanField(blank=True, default=False, null=True)),
                ('check_in', models.DateTimeField(blank=True, null=True)),
                ('check_out', models.DateTimeField(blank=True, null=True)),
                ('alien', models.OneToOneField(default=0, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='alien_parking', to='alien.alien')),
                ('parking', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='parking.parkingprofile')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
