# Generated by Django 3.2.8 on 2022-05-04 16:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0009_auto_20220312_2044'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parkingprofile',
            name='status',
        ),
    ]
