# Generated by Django 3.2.8 on 2022-05-05 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0011_auto_20220504_2011'),
    ]

    operations = [
        migrations.AddField(
            model_name='parkingprofile',
            name='status',
            field=models.CharField(blank=True, choices=[('Full', 'full'), ('NOT FULL', 'not full')], default='NOT FULL', max_length=55, null=True),
        ),
    ]
