# Generated by Django 3.2.8 on 2022-01-18 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CurrentLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(blank=True, default=False, max_length=55, null=True)),
                ('city', models.CharField(default=False, max_length=75, null=True)),
                ('region_name', models.CharField(default=False, max_length=75, null=True)),
                ('longitude', models.CharField(blank=True, default=False, max_length=20, null=True)),
                ('latitude', models.CharField(blank=True, default=False, max_length=20, null=True)),
            ],
        ),
    ]
