# Generated by Django 3.2.8 on 2022-01-10 19:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('location', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CurrentLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(blank=True, default=False, max_length=55, null=True)),
                ('city', models.CharField(default=False, max_length=75, null=True)),
                ('region_name', models.CharField(default=False, max_length=75, null=True)),
                ('longitude', models.CharField(blank=True, default=False, max_length=20, null=True)),
                ('latitude', models.CharField(blank=True, default=False, max_length=20, null=True)),
                ('user', models.OneToOneField(blank=True, default=False, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
