# Generated by Django 3.2.8 on 2022-02-11 17:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='currentlocation',
            name='city',
        ),
        migrations.RemoveField(
            model_name='currentlocation',
            name='country',
        ),
    ]
