# Generated by Django 3.2.8 on 2021-11-16 13:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0003_selectecountryandcity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='selectecountryandcity',
            name='city',
        ),
    ]
