# Generated by Django 3.2.8 on 2021-11-22 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0007_currentlocation_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='city_10',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='city',
            name='city_4',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='city',
            name='city_5',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='city',
            name='city_6',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='city',
            name='city_7',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='city',
            name='city_8',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='city',
            name='city_9',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
