# Generated by Django 3.2.8 on 2021-11-22 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0008_auto_20211122_2025'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='city_1',
            field=models.CharField(default=False, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='city',
            name='city_10',
            field=models.CharField(default=False, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='city',
            name='city_2',
            field=models.CharField(default=False, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='city',
            name='city_3',
            field=models.CharField(default=False, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='city',
            name='city_4',
            field=models.CharField(default=False, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='city',
            name='city_5',
            field=models.CharField(default=False, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='city',
            name='city_6',
            field=models.CharField(default=False, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='city',
            name='city_7',
            field=models.CharField(default=False, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='city',
            name='city_8',
            field=models.CharField(default=False, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='city',
            name='city_9',
            field=models.CharField(default=False, max_length=150, null=True),
        ),
    ]
