# Generated by Django 3.2.8 on 2021-11-22 18:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0009_auto_20211122_2027'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='city',
            name='city_10',
        ),
        migrations.RemoveField(
            model_name='city',
            name='city_4',
        ),
        migrations.RemoveField(
            model_name='city',
            name='city_5',
        ),
        migrations.RemoveField(
            model_name='city',
            name='city_6',
        ),
        migrations.RemoveField(
            model_name='city',
            name='city_7',
        ),
        migrations.RemoveField(
            model_name='city',
            name='city_8',
        ),
        migrations.RemoveField(
            model_name='city',
            name='city_9',
        ),
    ]
