# Generated by Django 3.2.8 on 2021-12-23 13:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('location', '0010_auto_20211122_2052'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='city_1',
            field=models.CharField(blank=True, default=False, max_length=75, null=True),
        ),
        migrations.AlterField(
            model_name='city',
            name='city_2',
            field=models.CharField(default=False, max_length=75, null=True),
        ),
        migrations.AlterField(
            model_name='city',
            name='city_3',
            field=models.CharField(blank=True, default=False, max_length=75, null=True),
        ),
        migrations.AlterField(
            model_name='currentlocation',
            name='city',
            field=models.CharField(default=False, max_length=75, null=True),
        ),
        migrations.AlterField(
            model_name='currentlocation',
            name='country',
            field=models.CharField(blank=True, default=False, max_length=55, null=True),
        ),
        migrations.AlterField(
            model_name='currentlocation',
            name='latitude',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='currentlocation',
            name='longitude',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='currentlocation',
            name='region_name',
            field=models.CharField(default=False, max_length=75, null=True),
        ),
        migrations.AlterField(
            model_name='currentlocation',
            name='user',
            field=models.OneToOneField(blank=True, default=False, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='getlocationmanual',
            name='country',
            field=models.CharField(blank=True, choices=[('Fa', 'French'), ('Bg', 'Belgium'), ('Sl', 'Switzerland ')], max_length=150, null=True),
        ),
    ]
