# Generated by Django 3.2.8 on 2021-12-26 16:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0011_auto_20211223_1547'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='getlocationmanual',
            name='city',
        ),
        migrations.RemoveField(
            model_name='selectecountryandcity',
            name='user',
        ),
        migrations.DeleteModel(
            name='City',
        ),
        migrations.DeleteModel(
            name='GetLocationManual',
        ),
        migrations.DeleteModel(
            name='SelecteCountryAndCity',
        ),
    ]
