# Generated by Django 3.2.8 on 2021-11-14 01:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True


