# Generated by Django 3.2.8 on 2021-11-16 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('currrent_location', '0004_remove_selectecountryandcity_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='selectecountryandcity',
            name='city',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
