# Generated by Django 3.2.8 on 2022-04-11 22:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rating', '0002_auto_20220411_2143'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rating',
            old_name='rat',
            new_name='rate',
        ),
    ]
