# Generated by Django 3.2.8 on 2022-02-19 19:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0003_auto_20220212_2213'),
        ('pharmacy', '0004_auto_20220119_2342'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pharmacy',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='pharmacy',
            name='longitude',
        ),
        migrations.AddField(
            model_name='pharmacy',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pharmacy_location', to='location.currentlocation'),
        ),
        migrations.AddField(
            model_name='pharmacy',
            name='status',
            field=models.IntegerField(choices=[(200, 'New'), (201, 'Approved'), (400, 'Rejected')], default=200),
        ),
    ]
