# Generated by Django 3.2.8 on 2022-05-04 18:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pharmacy', '0008_remove_pharmacy_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pharmacy',
            name='email',
        ),
        migrations.RemoveField(
            model_name='pharmacy',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='pharmacy',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='pharmacy',
            name='password',
        ),
        migrations.RemoveField(
            model_name='pharmacy',
            name='username',
        ),
        migrations.AddField(
            model_name='pharmacy',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
    ]
