# Generated by Django 3.2.8 on 2022-02-25 16:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_customuser_middle_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Country',
        ),
    ]
