# Generated by Django 3.2.8 on 2021-10-28 23:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_category_post'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='author',
        ),
        migrations.RemoveField(
            model_name='post',
            name='category',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='Post',
        ),
    ]
