# Generated by Django 3.2.8 on 2021-10-30 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_auto_20211029_0152'),
    ]

    operations = [
        migrations.CreateModel(
            name='CreateUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=150, null=True)),
                ('last_name', models.CharField(max_length=150, null=True)),
                ('username', models.CharField(max_length=150, null=True, unique=True)),
                ('password', models.CharField(max_length=150, unique=True)),
                ('email', models.EmailField(max_length=254, null=True, unique=True)),
            ],
        ),
    ]
