# Generated by Django 3.2.8 on 2021-10-30 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_createuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='createuser',
            name='address',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='createuser',
            name='is_verify',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='createuser',
            name='phone_number',
            field=models.CharField(max_length=11, null=True),
        ),
    ]
