# Generated by Django 3.2.8 on 2021-10-31 12:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_auto_20211030_2242'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CreateUser',
        ),
    ]
