# Generated by Django 3.2.8 on 2022-02-11 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alien', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='alien',
            name='country',
            field=models.CharField(blank=True, default=False, max_length=75, null=True),
        ),
    ]
