# Generated by Django 3.2.8 on 2022-02-19 19:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alien', '0004_auto_20220218_1900'),
    ]

    operations = [
        migrations.AddField(
            model_name='alien',
            name='mobile_numer',
            field=models.CharField(blank=True, max_length=15, null=True, validators=[django.core.validators.RegexValidator(message="Mobile number must be 10 digits starting with '01'.", regex='^\\d{11}$')]),
        ),
    ]
