# Generated by Django 3.2.8 on 2022-02-19 19:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alien', '0005_alien_mobile_numer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='alien',
            old_name='mobile_numer',
            new_name='mobile_number',
        ),
    ]
