# Generated by Django 3.2.8 on 2022-02-23 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alien', '0006_rename_mobile_numer_alien_mobile_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alien',
            name='residence',
        ),
        migrations.AddField(
            model_name='alien',
            name='latitude',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='alien',
            name='longitude',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
