# Generated by Django 3.2.8 on 2022-02-23 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alien', '0008_alien_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='alien',
            name='user_name',
            field=models.CharField(blank=True, max_length=75, null=True),
        ),
    ]
