# Generated by Django 3.2.8 on 2022-02-23 23:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alien', '0009_alien_user_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='alien',
            old_name='user_name',
            new_name='username',
        ),
    ]
