# Generated by Django 3.2.8 on 2022-02-24 14:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('alien', '0009_alien_user_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alien',
            name='user_name',
        ),
        migrations.AddField(
            model_name='alien',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='alien_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
