# Generated by Django 3.2.8 on 2022-02-25 15:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alien', '0010_auto_20220224_1613'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alien',
            name='user',
        ),
    ]
