# Generated by Django 3.2.8 on 2022-02-25 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alien', '0011_remove_alien_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='alien',
            name='username',
            field=models.CharField(max_length=10, null=True, unique=True),
        ),
    ]
