# Generated by Django 3.2.8 on 2022-02-25 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alien', '0012_alien_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alien',
            name='country',
            field=models.CharField(blank=True, choices=[('French', 'French'), ('Switzerland', 'Switzerland'), ('Belgium', 'Belgium')], default=False, max_length=75, null=True),
        ),
    ]
