# Generated by Django 3.2.8 on 2022-02-26 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alien', '0013_alter_alien_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='alien',
            name='gender',
            field=models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female'), ('P', 'Prefer not to answer')], max_length=75, null=True),
        ),
        migrations.AlterField(
            model_name='alien',
            name='country',
            field=models.CharField(blank=True, choices=[('FRA', 'French'), ('SWZ', 'Switzerland'), ('BLG', 'Belgium')], default=False, max_length=75, null=True),
        ),
    ]
