# Generated by Django 3.2.8 on 2021-12-28 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ResturantRegisterApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default=False, max_length=155, null=True)),
                ('street', models.CharField(max_length=100, verbose_name='street')),
                ('zip_code', models.CharField(max_length=100, verbose_name='zip code')),
                ('resturant_type', models.CharField(blank=True, default=False, max_length=255, null=True)),
                ('type', models.CharField(choices=[('Br', 'Branch'), ('Ev', 'Event'), ('Other', 'Other')], max_length=255)),
            ],
        ),
    ]
