# Generated by Django 3.2.8 on 2022-02-22 20:40

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified_at', models.DateTimeField(auto_now=True, null=True)),
                ('hidden', models.BooleanField(blank=True, default=False, null=True)),
                ('sandwiches', models.CharField(blank=True, choices=[('meat', 'meat'), ('chicks', 'chicks'), ('cheese', 'cheese')], default=False, max_length=155, null=True)),
                ('meal', models.CharField(blank=True, choices=[('meat', 'meat'), ('chicks', 'chicks'), ('cheese', 'cheese')], default=False, max_length=155, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ResturantProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified_at', models.DateTimeField(auto_now=True, null=True)),
                ('name', models.CharField(blank=True, default=False, max_length=150, null=True, validators=[django.core.validators.RegexValidator(message='Special characters and digits are now allowed.', regex='^[\\u0600-\\u065F\\u066A-\\u06EF\\u06FA-\\u06FFa-zA-Z]+[\\u0600-\\u065F\\u066A-\\u06EF\\u06FA-\\u06FFa-zA-Z ]*$')])),
                ('mobile_number', models.CharField(blank=True, max_length=15, null=True, validators=[django.core.validators.RegexValidator(message="Mobile number must be 10 digits starting with '01'.", regex='^\\d{11}$')])),
                ('address', models.CharField(blank=True, default=False, max_length=155, null=True)),
                ('email', models.EmailField(blank=True, default=False, max_length=254, null=True, unique=True)),
                ('country', models.CharField(blank=True, default=False, max_length=55, null=True)),
                ('city', models.CharField(default=False, max_length=75, null=True)),
                ('longitude', models.CharField(blank=True, max_length=20, null=True)),
                ('latitude', models.CharField(blank=True, max_length=20, null=True)),
                ('start_working', models.CharField(blank=True, default=False, max_length=35, null=True)),
                ('end_working', models.CharField(blank=True, default=False, max_length=35, null=True)),
                ('occupied_table', models.CharField(blank=True, max_length=35, null=True)),
                ('available_table', models.CharField(blank=True, max_length=35, null=True)),
                ('status', models.CharField(choices=[(201, 'Open'), (405, 'Closed')], default='Open', max_length=155)),
                ('resturant_status', models.IntegerField(choices=[(200, 'New'), (201, 'Approved'), (400, 'Rejected')], default=200)),
                ('hidden', models.BooleanField(default=False)),
                ('menu', models.ForeignKey(blank=True, default=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='restaurant.menu')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ResturantBookingTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified_at', models.DateTimeField(auto_now=True, null=True)),
                ('hidden', models.BooleanField(blank=True, default=False, null=True)),
                ('user_mobile_number', models.CharField(blank=True, max_length=11, null=True)),
                ('table_booking_number', models.IntegerField(blank=True, null=True)),
                ('chair_booking_number', models.IntegerField(blank=True, null=True)),
                ('booking_hourse', models.CharField(blank=True, max_length=150, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DelivaryOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified_at', models.DateTimeField(auto_now=True, null=True)),
                ('hidden', models.BooleanField(blank=True, default=False, null=True)),
                ('order_count', models.IntegerField(blank=True, null=True)),
                ('user_mobile_number', models.CharField(blank=True, max_length=11, null=True)),
                ('alian', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('resturant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='restaurant.resturantprofile')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
