# Generated by Django 3.2.8 on 2022-02-22 19:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='delivaryorder',
            old_name='user',
            new_name='alian',
        ),
        migrations.AddField(
            model_name='resturantprofile',
            name='end_working',
            field=models.CharField(blank=True, default=False, max_length=35, null=True),
        ),
        migrations.AddField(
            model_name='resturantprofile',
            name='latitude',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='resturantprofile',
            name='longitude',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='resturantprofile',
            name='mobile_number',
            field=models.CharField(blank=True, max_length=15, null=True, validators=[django.core.validators.RegexValidator(message="Mobile number must be 10 digits starting with '01'.", regex='^\\d{11}$')]),
        ),
        migrations.AddField(
            model_name='resturantprofile',
            name='resturant_status',
            field=models.IntegerField(choices=[(200, 'New'), (201, 'Approved'), (400, 'Rejected')], default=200),
        ),
        migrations.AddField(
            model_name='resturantprofile',
            name='start_working',
            field=models.CharField(blank=True, default=False, max_length=35, null=True),
        ),
        migrations.AlterField(
            model_name='resturantprofile',
            name='available_table',
            field=models.CharField(blank=True, max_length=35, null=True),
        ),
        migrations.AlterField(
            model_name='resturantprofile',
            name='city',
            field=models.CharField(default=False, max_length=75, null=True),
        ),
        migrations.AlterField(
            model_name='resturantprofile',
            name='country',
            field=models.CharField(blank=True, default=False, max_length=55, null=True),
        ),
        migrations.AlterField(
            model_name='resturantprofile',
            name='hidden',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='resturantprofile',
            name='name',
            field=models.CharField(blank=True, default=False, max_length=150, null=True, validators=[django.core.validators.RegexValidator(message='Special characters and digits are now allowed.', regex='^[\\u0600-\\u065F\\u066A-\\u06EF\\u06FA-\\u06FFa-zA-Z]+[\\u0600-\\u065F\\u066A-\\u06EF\\u06FA-\\u06FFa-zA-Z ]*$')]),
        ),
        migrations.AlterField(
            model_name='resturantprofile',
            name='occupied_table',
            field=models.CharField(blank=True, max_length=35, null=True),
        ),
        migrations.DeleteModel(
            name='ResturantRegisterApplication',
        ),
    ]
