# Generated by Django 3.2.8 on 2022-04-11 19:02

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rating', '0001_initial'),
        ('alien', '0014_auto_20220226_2135'),
        ('restaurant', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified_at', models.DateTimeField(auto_now=True, null=True)),
                ('hidden', models.BooleanField(blank=True, default=False, null=True)),
                ('alien', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='order_alien', to='alien.alien')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RestaurantBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified_at', models.DateTimeField(auto_now=True, null=True)),
                ('hidden', models.BooleanField(blank=True, default=False, null=True)),
                ('start_date', models.DateTimeField(blank=True, null=True)),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(blank=True, choices=[(101, 'New'), (210, 'Open'), (410, 'Closed')], default=101, max_length=20, null=True)),
                ('alien', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='alien_restaurant', to='alien.alien')),
                ('rating', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='rating.rating')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RestaurantProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified_at', models.DateTimeField(auto_now=True, null=True)),
                ('name', models.CharField(blank=True, default=False, max_length=150, null=True, validators=[django.core.validators.RegexValidator(message='Special characters and digits are now allowed.', regex='^[\\u0600-\\u065F\\u066A-\\u06EF\\u06FA-\\u06FFa-zA-Z]+[\\u0600-\\u065F\\u066A-\\u06EF\\u06FA-\\u06FFa-zA-Z ]*$')])),
                ('mobile_number', models.CharField(blank=True, max_length=15, null=True, validators=[django.core.validators.RegexValidator(message="Mobile number must be 10 digits starting with '01'.", regex='^\\d{11}$')])),
                ('address', models.CharField(blank=True, default=False, max_length=155, null=True)),
                ('email', models.EmailField(blank=True, default=False, max_length=254, null=True, unique=True)),
                ('country', models.CharField(blank=True, default=False, max_length=55, null=True)),
                ('city', models.CharField(default=False, max_length=75, null=True)),
                ('longitude', models.CharField(blank=True, max_length=20, null=True)),
                ('latitude', models.CharField(blank=True, max_length=20, null=True)),
                ('start_working', models.CharField(blank=True, default=False, max_length=35, null=True)),
                ('end_working', models.CharField(blank=True, default=False, max_length=35, null=True)),
                ('occupied_table', models.CharField(blank=True, max_length=35, null=True)),
                ('available_table', models.CharField(blank=True, max_length=35, null=True)),
                ('restaurant_status', models.CharField(blank=True, choices=[(201, 'Open'), (405, 'Closed')], default=201, max_length=155, null=True)),
                ('status', models.IntegerField(choices=[(200, 'New'), (201, 'Approved'), (400, 'Rejected')], default=200)),
                ('hidden', models.BooleanField(default=False)),
                ('menu', models.ForeignKey(blank=True, default=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='restaurant.menu')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='resturantbookingtable',
            name='user',
        ),
        migrations.RemoveField(
            model_name='resturantprofile',
            name='menu',
        ),
        migrations.DeleteModel(
            name='DelivaryOrder',
        ),
        migrations.DeleteModel(
            name='ResturantBookingTable',
        ),
        migrations.DeleteModel(
            name='ResturantProfile',
        ),
        migrations.AddField(
            model_name='deliveryorder',
            name='restaurant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='restaurant.restaurantprofile'),
        ),
    ]
