# Generated by Django 3.2.8 on 2022-01-18 22:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='delivaryorder',
            old_name='user',
            new_name='alian',
        ),
    ]
