# Generated by Django 3.2.8 on 2022-01-10 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='resturanprofile',
            name='status',
            field=models.CharField(choices=[(201, 'Open'), (405, 'Closed')], default='Open', max_length=155),
        ),
        migrations.AlterField(
            model_name='resturantregisterapplication',
            name='status',
            field=models.IntegerField(choices=[(200, 'New'), (201, 'Approved'), (400, 'Rejected')], default=200),
        ),
    ]
