# Generated by Django 3.2.8 on 2022-01-18 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0002_rename_user_delivaryorder_alian'),
    ]

    operations = [
        migrations.AddField(
            model_name='resturantprofile',
            name='latitude',
            field=models.CharField(blank=True, default=False, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='resturantprofile',
            name='longitude',
            field=models.CharField(blank=True, default=False, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='resturantprofile',
            name='region_name',
            field=models.CharField(default=False, max_length=75, null=True),
        ),
        migrations.AlterField(
            model_name='resturantprofile',
            name='city',
            field=models.CharField(default=False, max_length=75, null=True),
        ),
        migrations.AlterField(
            model_name='resturantprofile',
            name='country',
            field=models.CharField(blank=True, default=False, max_length=55, null=True),
        ),
    ]
