# Generated by Django 3.2.8 on 2022-01-11 07:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0002_auto_20220110_2205'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ResturanProfile',
            new_name='ResturantProfile',
        ),
    ]
