# Generated by Django 3.2.8 on 2022-01-19 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0003_auto_20220119_0123'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resturantregisterapplication',
            name='end_working',
            field=models.CharField(blank=True, max_length=155, null=True),
        ),
        migrations.AlterField(
            model_name='resturantregisterapplication',
            name='start_working',
            field=models.CharField(blank=True, max_length=155, null=True),
        ),
    ]
