# Generated by Django 3.2.8 on 2022-01-11 09:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0003_remove_currentlocation_user'),
        ('restaurant', '0003_rename_resturanprofile_resturantprofile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resturantregisterapplication',
            name='city',
        ),
        migrations.RemoveField(
            model_name='resturantregisterapplication',
            name='country',
        ),
        migrations.RemoveField(
            model_name='resturantregisterapplication',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='resturantregisterapplication',
            name='longitude',
        ),
        migrations.AddField(
            model_name='resturantregisterapplication',
            name='location',
            field=models.ForeignKey(default=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='location.currentlocation'),
        ),
    ]
