# Generated by Django 3.2.8 on 2022-02-12 21:51

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('location', '0003_auto_20220212_2213'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified_at', models.DateTimeField(auto_now=True, null=True)),
                ('hidden', models.BooleanField(blank=True, default=False, null=True)),
                ('name', models.CharField(blank=True, max_length=150, null=True, validators=[django.core.validators.RegexValidator(message='Special characters and digits are now allowed.', regex='^[\\u0600-\\u065F\\u066A-\\u06EF\\u06FA-\\u06FFa-zA-Z]+[\\u0600-\\u065F\\u066A-\\u06EF\\u06FA-\\u06FFa-zA-Z ]*$')])),
                ('email', models.EmailField(blank=True, default=False, max_length=254, null=True, unique=True)),
                ('address_detal', models.CharField(blank=True, default=False, max_length=250, null=True)),
                ('phone_number', models.CharField(blank=True, default=False, max_length=150, null=True, validators=[django.core.validators.RegexValidator(message="Mobile number must be 10 digits starting with '01'.", regex='^\\d{11}$')])),
                ('location', models.ForeignKey(default=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='location.currentlocation')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
