# Generated by Django 3.2.8 on 2022-04-02 12:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hotel', '0002_auto_20220212_2353'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='user',
        ),
        migrations.RemoveField(
            model_name='hotel',
            name='address_detal',
        ),
        migrations.RemoveField(
            model_name='hotel',
            name='location',
        ),
        migrations.RemoveField(
            model_name='room',
            name='hotel',
        ),
        migrations.AddField(
            model_name='booking',
            name='check_in',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='hotel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hotel.hotel'),
        ),
        migrations.AddField(
            model_name='hotel',
            name='bed_number',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hotel',
            name='latitude',
            field=models.CharField(blank=True, default=False, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='hotel',
            name='longitude',
            field=models.CharField(blank=True, default=False, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='hotel',
            name='room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='room_number', to='hotel.room'),
        ),
        migrations.AddField(
            model_name='hotel',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='room',
            name='floor',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='check_out',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='status',
            field=models.CharField(blank=True, choices=[(100, 'New'), (201, 'Approve'), (400, 'Rejected')], default=100, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='room',
            name='status',
            field=models.CharField(blank=True, choices=[(100, 'not_completed'), (400, 'complete')], default=False, max_length=150, null=True),
        ),
    ]
