# Generated by Django 3.2.8 on 2022-04-02 14:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0004_auto_20220402_1608'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hotel',
            name='bed_number',
        ),
        migrations.RemoveField(
            model_name='hotel',
            name='room',
        ),
    ]
