# Generated by Django 3.2.8 on 2022-05-24 17:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ParkPofile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified_at', models.DateTimeField(auto_now=True, null=True)),
                ('hidden', models.BooleanField(blank=True, default=False, null=True)),
                ('name', models.CharField(blank=True, max_length=150, null=True)),
                ('mobile_number', models.IntegerField(blank=True, max_length=11, null=True)),
                ('country', models.CharField(blank=True, choices=[('FRA', 'French'), ('SWZ', 'Switzerland'), ('BLG', 'Belgium')], default=False, max_length=55, null=True)),
                ('city', models.CharField(blank=True, max_length=55, null=True)),
                ('status', models.CharField(blank=True, choices=[(201, 'Open'), (405, 'Closed')], default=201, max_length=155, null=True)),
                ('address', models.TextField(blank=True, max_length=350, null=True)),
                ('user', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='user_park', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
